### ISSUE TITLE
External sources for SNI maps

### ISSUE THREAD

**Issue by friesoft** [Icinga/icingaweb2-module-x509#1]
How does this plugin work with one ip serving multiple domains (vhosts) and thus multiple different certificates? 

I guess the plugin does some sort of openssl s_client on the found IP/Port combinations => Apache will only answer with the first matching certificate afaik

I couldn't find any answer to this in the docs.

**Comment by friesoft** [comment]
Can those maps be imported? We would love to use this Module but we would like to use it more like "Here are our ips with those domains running on them - please check those"

**Comment by lippserd** [comment]
The module works with INI files. The `jobs.ini` holds configuration regarding jobs:

```
[example-network]
cidrs = "10.0.1.0/24"
ports = "443, 636"
```

And then there's `sni.ini` which has the IP to hostnames map:

```
[10.0.1.10]
hostnames = "host.example.domain, server.example.domain"
```

Does this work four you?

**Comment by TheFlyingCorpse** [comment]
What about:
- Query against the active hostlist in icinga(web)2, preferably with wildcard support.
- Query against director, again with wilcard support.
- Query against a custom table in some database.
-- For example we've got PowerDNS as secondary DNS lookup server just for figuring out what we've got to update the CMDB which in turns updates Icinga2 through Director.

It would help maintain what the entries about, in our setup we've got vhosts as dedicated hosts (and any local checks for the website(s) are executed on the icinga2 node through a function).

**Comment by yoshi314** [comment]
I could definitely use some automation here, i've got way too many vhosts to manage.

**Comment by Al2Klimov** [comment]
Hello all and thank you for your interest in an automation of this feature!

At the moment there isn't any, you but could auto-generate that INI file from your desired data source.

Best,
AK

**Comment by Al2Klimov** [comment]
@lippserd What about hooks?

**Comment by nilmerg** [comment]
This will be merged soon into master. Note that there is now a referenced PR for the monitoring module above. This will also be part of the master soon and then be required in order to utilize it as SNI source.
