### ISSUE TITLE
Redesign x509 dashboard

### ISSUE THREAD

**Issue by yhabteab** [Icinga/icingaweb2-module-x509#100]
## Describe the bug

As you can see from the screenshot, the dashboard doesn't really look nice. Since the colors don't really differ from the background, the donuts don't really look informative. Therefore, we should consider new colors which will look nicely in both light and dark themes.

<img width="1231" alt="Bildschirmfoto 2021-11-25 um 12 15 07" src="https://user-images.githubusercontent.com/57616252/143443341-3fdc41d5-6c39-40ae-9cef-3ee0e20168fa.png">

**Comment by flourish86** [comment]
I created some palettes, that work better across dark/light mode.

# Dirty

Darker green provides too little contrast for dark mode.

![dirty-dark](https://user-images.githubusercontent.com/6977434/217542696-d1a9320f-c2db-42f9-a500-c6a8a9f11dab.png)
![dirty-light](https://user-images.githubusercontent.com/6977434/217542702-39069f7b-c02a-41d8-ba9f-cda67cae5757.png)


# Pastel

Best contrast for both modes, but might be a little too light for light mode. Besides that the colors are a little far away from the remaining UI colors.

![pastel-dark](https://user-images.githubusercontent.com/6977434/217542732-673149ea-be2d-43dc-b9e8-7e890241e2f8.png)
![pastel-light](https://user-images.githubusercontent.com/6977434/217542737-093f0365-fa5d-404a-ad41-5eea5b4fbf13.png)

# Rainbow

Most balanced, not too vibrant. But therefore contrast suffers a bit.

![rainbow-dark](https://user-images.githubusercontent.com/6977434/217542752-d8a1ad3e-5b97-418f-a8ab-59baaac702fc.png)
![rainbow-light](https://user-images.githubusercontent.com/6977434/217542754-8ccf4c8e-ddfb-49d1-919c-ad39f2cafa3f.png)

# Saturated

Pretty vibrant. Also high contrast in light and dark mode, but almost like “pastel” standing out too much from the rest of the UI.

![saturated-dark](https://user-images.githubusercontent.com/6977434/217542802-74e2cce7-8d5b-4da8-bb07-878d9c035a2e.png)
![saturated-light](https://user-images.githubusercontent.com/6977434/217542808-42de69ef-7f32-454d-8792-a27485166bef.png)

I chose the Rainbow color palette, as it integratres well into the surrounding UI but also delivers a solid contrast in both view modes.
