### ISSUE TITLE
Can we add the ability for this module to alert when certificates are about to expire

### ISSUE THREAD

**Issue by gettoknowmii** [Icinga/icingaweb2-module-x509#109]
## Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. Ex. I'm always using this feature but am missing [...]
This module shows all the certificates that it discover on the web GUI. how can i configure it to alert automatically, when certificates are about to expire

## Describe the solution you'd like
i want to be able to receive alerts after every job scan for expiring certificates within 30 days

**Comment by nilmerg** [comment]
Integration into the monitoring is described in the [documentation](https://icinga.com/docs/icinga-certificate-monitoring/latest/doc/10-Monitoring/).

Since I got no feedback for my first comment and the OP doesn't ask for anything specific, the documentation should be what's needed. Closing.
