### ISSUE TITLE
Adding the source for icons.ttf

### ISSUE THREAD

**Issue by daku69** [Icinga/icingaweb2-module-x509#111]
## Describe the bug
Please adding the source for icons.ttf. To build debian package, must for every binary the source by integrated.

## To Reproduce
Show:
https://lintian.debian.org/sources/icingaweb2-module-x509?version=20190125-3

Thanks

**Comment by daku69** [comment]
No, unfortunately not. They must be in the sourcepackage.

**Comment by nilmerg** [comment]
With the next release the icons will be gone here and be part of icinga-php-library instead, with sources.
