### ISSUE TITLE
icingacli x509 jobs run error: PHP Fatal error:  Uncaught Error: Class "ipl\Scheduler\Scheduler" not found

### ISSUE THREAD

**Issue by whackl** [Icinga/icingaweb2-module-x509#139]
After installation and configuration of the database backend without any errors the following php error is thrown using the jobs run command 

# icingacli x509 jobs run
PHP Fatal error:  Uncaught Error: Class "ipl\Scheduler\Scheduler" not found in /usr/share/icingaweb2/modules/x509/application/clicommands/JobsCommand.php:38
Stack trace:
#0 /usr/share/php/Icinga/Cli/Loader.php(267): Icinga\Module\X509\Clicommands\JobsCommand->runAction()
#1 /usr/share/php/Icinga/Application/Cli.php(164): Icinga\Cli\Loader->dispatch()
#2 /usr/share/php/Icinga/Application/Cli.php(154): Icinga\Application\Cli->dispatchOnce()
#3 /usr/bin/icingacli(7): Icinga\Application\Cli->dispatch()
#4 {main}
  thrown in /usr/share/icingaweb2/modules/x509/application/clicommands/JobsCommand.php on line 38

Fatal error: Uncaught Error: Class "ipl\Scheduler\Scheduler" not found in /usr/share/icingaweb2/modules/x509/application/clicommands/JobsCommand.php:38
Stack trace:
#0 /usr/share/php/Icinga/Cli/Loader.php(267): Icinga\Module\X509\Clicommands\JobsCommand->runAction()
#1 /usr/share/php/Icinga/Application/Cli.php(164): Icinga\Cli\Loader->dispatch()
#2 /usr/share/php/Icinga/Application/Cli.php(154): Icinga\Application\Cli->dispatchOnce()
#3 /usr/bin/icingacli(7): Icinga\Application\Cli->dispatch()
#4 {main}
  thrown in /usr/share/icingaweb2/modules/x509/application/clicommands/JobsCommand.php on line 38

It should list the jobs configured as I expect

## Your Environment

Icinga Web 2 Version	2.11.1
PHP-Version	8.0.25

Geladene Bibliotheken
icinga/icinga-php-library	0.10.0
icinga/icinga-php-thirdparty	0.11.0

Geladene Module
director		1.9.1	
graphite		1.1.0	
incubator		0.17.0	
monitoring	2.11.1	
nagvis		1.1.1	
x509		1.1.2	

The System is running on Ubuntu 22.04 LTS

The latest Icinga-php-library is 0.10.0 , in the install documentation it is listed as 0.11.0

**Comment by slalomsk8er** [comment]
Try to add https://github.com/Icinga/ipl-scheduler or use a release (https://github.com/Icinga/icingaweb2-module-x509/releases/tag/v1.1.2) and not master.

**Comment by bigfreak85** [comment]
use the stable release works.
thx
