### ISSUE TITLE
Filter certificates by valid/invalid state in the usage overview

### ISSUE THREAD

**Issue by Tuxdiver** [Icinga/icingaweb2-module-x509#14]
Feature Request:

I would like to filter the certificates under "Certificate Usage" by the ok/not ok state (shown with the green / red icon in the first row) to find "bad" certs faster.

**Comment by lippserd** [comment]
Hi,

Thanks for the report. Will be implemented in a second. Please star the module, if you like it.

Best,
Eric

**Comment by lippserd** [comment]
Make sure to use the words `yes` or `no` for the `valid` filter column.

**Comment by Tuxdiver** [comment]
perfect, works :-)
Thanks a lot!
