### ISSUE TITLE
Add exclusion for Jobs

### ISSUE THREAD

**Issue by wp-perc** [Icinga/icingaweb2-module-x509#140]
Sometimes, I need to scan a whole subnet except some specific IPs.
E.G.: scan 192.168.1.0/24 except .23, .55, .100, .133, .199.

Right now, I have to calculate all the subnets in the right way, and maybe define other jobs.
What I'd like is to have an exclusion list.
E.G.:
CIDR: 192.168.1.0/24
Exclusions: 192.168.1.23, 192.168.1.55, 192.168.1.100, 192.168.1.133, 192.168.1.199.

**Comment by yhabteab** [comment]
Duplicated of https://github.com/Icinga/icingaweb2-module-x509/issues/11
