### ISSUE TITLE
Issues with PostgreSQL 

### ISSUE THREAD

**Issue by fl0wx** [Icinga/icingaweb2-module-x509#146]
## Describe the bug
I discovered some issues while using postgresl. Neither certificate import nor certificate dashboard works as expected. 

**Dashboard Issue:**
![image](https://user-images.githubusercontent.com/2448081/213127310-0134aad9-f9aa-4a01-a721-db892142b8e6.png)
and in the given schema sql:
`CREATE TYPE boolenum AS ENUM ('n', 'y');`
So there seems a mismatch.

**Certificate Import:**
![image](https://user-images.githubusercontent.com/2448081/213127484-a597738c-700e-43b2-a652-097a936d06dc.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):
![image](https://user-images.githubusercontent.com/2448081/213127848-a4109e1c-fbbe-4458-8781-962183abf6de.png)
* Web browser used: Chrome 
* Icinga 2 version used (`icinga2 --version`): r2.11.3-1
* PHP version used (`php --version`): PHP 7.3.31-1~deb10u2
* Server operating system and version: Debia 10.13

**Comment by yhabteab** [comment]
Hii @fl0wx, thanks for the report.

PostgreSQL support hasn't yet been released. Therefore you need to check out the master branch.

**Comment by fl0wx** [comment]
@yhabteab  thanks for the fast reply. Master branch works :) any estimated release time?

**Comment by yhabteab** [comment]
Hii, can't tell you for sure but here is the roadmap for the upcoming release. https://github.com/Icinga/icingaweb2-module-x509/milestone/5
