### ISSUE TITLE
icinga-php-library 0.11.0 no released yet

### ISSUE THREAD

**Issue by Gninieb** [Icinga/icingaweb2-module-x509#148]
## Is your feature request related to a problem? Please describe.
The required icinga-php-library is not available yet. 

## Describe the solution you'd like
Do not accept new braches into the stable brach until the dependencies can be resolved.

## Describe alternatives you've considered
accept unstable/0.11.0-dev brache at dependency check

**Comment by moreamazingnick** [comment]
you checked out the master branch, requirements of master can be higher that available modules/libraries

but anyway icinga-php-library 0.11 was released 4 days ago.

**Comment by nilmerg** [comment]
Indeed.
