### ISSUE TITLE
PDOException in /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php:402 'ctime' doesn't have a default value

### ISSUE THREAD

**Issue by Darkentik** [Icinga/icingaweb2-module-x509#157]
## Describe the bug
First i installed the x509 module and prepared the mysql db with the import of the schema.
![grafik](https://user-images.githubusercontent.com/9421857/222357794-8fd04935-c8b3-44cb-9525-e7d969bb976e.png)

As mentioned in the [docs](https://icinga.com/docs/icinga-certificate-monitoring/latest/doc/03-Configuration/#importing-ca-certificates), i wanted to import a ca certificate.
But when using the command i got the error
```
sysmonweb01-a.test.hal01.de.mycompany.local: /etc/icingaweb2/modules/ $ icingacli x509 import --file /usr/local/share/ca-certificates/RootCA_mycompany.local.cer
ERROR: PDOException in /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php:402 with message: SQLSTATE[HY000]: General error: 1364 Field 'ctime' doesn't have a default value
```

Is this a problem because we separate the services into single virtual machines and i can only import direct on the mariadb server? But there isn't the icingacli installed. I thought that i can handle this from the icingaweb2 server while configuring the backend for the module x509 to find the mariadb server over network.

## Your Environment
* Icingaweb2 Server with Apache2
* Icinga2 Master
* MariaDB Server with all DBs for Icinga2,Icingaweb2+Modules
* Network with the Icinga2 Agents

* Icinga Web 2 version and modules (System - About):
* Web browser used: Firefox 110.0 (64-Bit) on Xubuntu
* Icinga 2 version used (`icinga2 --version`):
``` 
icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.6-1)

Copyright (c) 2012-2023 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Debian GNU/Linux
  Platform version: 11 (bullseye)
  Kernel: Linux
  Kernel version: 5.10.0-15-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 10.2.1
  Build host: runner-hh8q3bz2-project-575-concurrent-0
  OpenSSL version: OpenSSL 1.1.1n  15 Mar 2022

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```
* PHP version used (`php --version`): 
``` 
PHP 7.4.33 (cli) (built: Feb 22 2023 20:07:47) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.33, Copyright (c), by Zend Technologies 
```
* Server operating system and version: see above in icinga2 version output

## Additional context
Be aware that we are separating the services to single virtual machines all in the same subnet.

**Comment by Darkentik** [comment]
When i configure my mariadb server in /etc/mysql/mariadb.conf.d/50-server.cnf with the option sql_method="" then i can import certs.

But this dirty hack cannot be the solution.
Please help me to find a clean solution to fix this on fresh installation.

Side info:
While using this dirty hack with sql_metho="" i cannot run scan jobs too.

error:
```
sysmonweb01-a.test.hal01.de.mycompany.local: /etc/icingaweb2/modules/ $ icingacli x509 scan --job testjob01
ERROR: RuntimeException in /usr/share/icingaweb2/modules/x509/library/X509/CertificateUtils.php:374 with message: Trust store is empty
```
The trust store isnt empty because i imported my ca before.
For me it seems that the module has some bugs. Maybe only on debian bullseye? I dont know. :-/

**Comment by yhabteab** [comment]
Hallo @Darkentik, thanks for the report. Please update your master branch. It's fixed [here](https://github.com/Icinga/icingaweb2-module-x509/pull/138/commits/51143a7b2eb941fd62e8c07ca2f0ffda15d1b145)

**Comment by yhabteab** [comment]
NM! Which module version are you using? If you imported the schema file from the master branch, you must also use the master branch.

**Comment by Darkentik** [comment]
Hey @yhabteab thanks for the fast reply. :)
What means "NW!"?
I am using the raw URL from the master branch from this official repo here.
Ant the module is installed directly from the latest release link here.

**Comment by yhabteab** [comment]
> What means "NM!"?

It means ignore the first comment I posted.

> I am using the [raw URL](https://raw.githubusercontent.com/Icinga/icingaweb2-module-x509/master/etc/schema/mysql.schema.sql) from the master branch from this official repo here.
> And the module is installed directly from the[ release page](https://github.com/Icinga/icingaweb2-module-x509/releases) with [link for v1.1.2.tar.gz here](https://github.com/Icinga/icingaweb2-module-x509/archive/refs/tags/v1.1.2.tar.gz).

That's the problem! The schema file of the master branch won't work correctly with versions other than the master. Please use the schema file from [the release tag](https://github.com/Icinga/icingaweb2-module-x509/blob/v1.1.2/etc/schema/mysql.schema.sql) you are using.

**Comment by Darkentik** [comment]
Ah! Ok i have learned something here. :)
In the tunnel i did not think about this. I thank you!
