### ISSUE TITLE
Check command

### ISSUE THREAD

**Issue by matthenning** [Icinga/icingaweb2-module-x509#16]
It would be great to have a check command to define certain certificates as services to enable notifications etc.

Examples:

`check_x509 --host host.fqdn.de` to check hosts via SNI

`check_x509 --ip 10.10.10.10` to check hosts via IP.

**Comment by lippserd** [comment]
Hi,

Thanks for the report. Indeed, this is a missing piece.

Best,
Eric

**Comment by widhalmt** [comment]
+1 from me and an extra +1 from a customer where I installed this module recently. 

/ref/NC/554321

**Comment by Al2Klimov** [comment]
And AFAIK this customer would even pay for it.

**Comment by Al2Klimov** [comment]
... if there would be something to pay for – there is already a check plugin for this:

https://github.com/matteocorti/check_ssl_cert

**Comment by lippserd** [comment]
There's no need to require an extra check plugin which validates the certificates again. We do have everything we need in our database and should use that for the module's check command.

**Comment by dnsmichi** [comment]
Works as expected.

```
-bash-4.2$ '/usr/bin/icingacli' 'x509' 'check' 'host' '--host' 'www.icinga.com' '--ip' '185.11.254.90' --warning 6m
OK - *.icinga.com expires in 223 days|'*.icinga.com'=962;1185;1066;0;1185
```
