### ISSUE TITLE
IP Text wrong symbols

### ISSUE THREAD

**Issue by Alex64798** [Icinga/icingaweb2-module-x509#172]
## Describe the bug
Since the update to the 1.2.1, the certificates analyzed by the jobs display a cryptic IP address in the dashboard

## To Reproduce
Go to "Certificate Monitoring" --> "Certificate Usage" and then look at the IP column

## Screenshots
![image](https://user-images.githubusercontent.com/86724320/231473865-829f04f0-45a1-475d-8ef5-b6d07b976f61.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.11.4
* Web browser used: Chrome & Firefox
* Icinga 2 version used (`icinga2 --version`): icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.7-1)
* PHP version used (`php --version`): 7.3.33
* Server operating system and version: CemtOS 7

**Comment by Alex64798** [comment]
> Hallo@Alex64798, danke für den Bericht. Hast du dieses Modul mit git installiert? Wenn ja, könnte ich Ihnen einen Patch zur Verfügung stellen, der das behebt.

Yes i have installed the update over git.

**Comment by yhabteab** [comment]
Please download this to the x509 module root directory, which is by default `/usr/share/icingaweb2/modules/x509/`, but if you have a different installation path, please adjust it accordingly. [ip-behaviour.patch](https://github.com/Icinga/icingaweb2-module-x509/files/11212436/ip-behaviour.patch)

Then you can run the following command. `git apply ip-behaviour.patch`

**Comment by Alex64798** [comment]
> Please download this to the x509 module root directory, which is by default `/usr/share/icingaweb2/modules/x509/`, but if you have a different installation path, please adjust it accordingly. [ip-behaviour.patch](https://github.com/Icinga/icingaweb2-module-x509/files/11212436/ip-behaviour.patch)
> 
> Then you can run the following command. `git apply ip-behaviour.patch`

The Patch works for me 👍
