### ISSUE TITLE
Service check failing with "ERROR: Cannot read enabled modules"

### ISSUE THREAD

**Issue by necarnot** [Icinga/icingaweb2-module-x509#176]
Hello,

[Icinga2 2.11.4, Director 1.10.2, icingaweb2-module-x509 1.2.1-1+debian11]
[The only thing I've changed is this patch : https://github.com/Icinga/icingaweb2-module-x509/issues/172]

I've successfully installed and set up this module : 
- the scan of subnets and SNI are working fine
- I'm following the very precise doc to integrate all this into Icinga via Director, and it's looking good (my host objects and services are created)
- When trying to check a service, I get the following error :

```
ERROR: Cannot read enabled modules. Config directory "/etc/icingaweb2" is not readable

Uncaught Error: Call to a member function select() on null in /usr/share/icingaweb2/modules/director/library/Director/Monitoring.php:141
Stack trace:
#0 /usr/share/icingaweb2/modules/director/library/Director/Monitoring.php(41): Icinga\Module\Director\Monitoring->prepareServiceKeyColumnQuery()
#1 /usr/share/icingaweb2/modules/director/library/Director/Monitoring.php(78): Icinga\Module\Director\Monitoring->hasService()
#2 /usr/share/icingaweb2/modules/director/application/controllers/HostController.php(37): Icinga\Module\Director\Monitoring->authCanEditService()
#3 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ActionController.php(57): Icinga\Module\Director\Controllers\HostController->checkDirectorPermissions()
#4 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(64): Icinga\Module\Director\Web\Controller\ActionController->init()
#5 /usr/share/php/Icinga/Web/Controller/ActionController.php(170): Icinga\Module\Director\Web\Controller\ObjectCont

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}
```

I can not reproduce it by asking for an immediate re-schedule, but I can reproduce it by removing a host and re-syncing.

This OS is a Debian 11, and all has been installed from the package manager.
The permissions are these : 
```bash
# ls -la /etc/icingaweb2/
total 40
drwxrws---  5 root     icingaweb2 4096  7 avril 16:47 .
drwxr-xr-x 90 root     root       4096 27 avril 16:46 ..
-rw-rw----  1 www-data icingaweb2  159  6 févr. 16:26 authentication.ini
-rw-rw----  1 www-data icingaweb2  190 24 janv. 14:19 config.ini
drwxrws---  3 www-data icingaweb2 4096  7 avril 16:47 dashboards
drwxrws---  2 www-data icingaweb2 4096 27 avril 16:39 enabledModules
-rw-rw----  1 www-data icingaweb2   81 24 janv. 14:19 groups.ini
drwxrws---  7 root     icingaweb2 4096 27 avril 12:08 modules
-rw-rw----  1 www-data icingaweb2  978 27 avril 12:07 resources.ini
-rw-rw----  1 www-data icingaweb2  101  6 févr. 16:17 roles.ini
```

Apache2 is running as www-data.
icinga2 is running as nagios.

I tried to add nagios into the icingaweb2 group, to no avail : 
```bash
# id www-data
uid=33(www-data) gid=33(www-data) groupes=33(www-data),119(icingaweb2)
# id nagios
uid=108(nagios) gid=114(nagios) groupes=114(nagios),119(icingaweb2)
```

Actually, I'm not even sure to know which process / which user is trying to reach the /etc/icingaweb2 ?

**Comment by yhabteab** [comment]
Hi @necarnot, thanks for your report, though this issue isn't related to this module in any way. You simply have a general permission problem. Have you restarted your **php-fpm** then? If that still doesn't help, please submit your question [here](https://community.icinga.com).

**Comment by necarnot** [comment]
Hello @yhabteab ,

As a matter of fact, I wasn't able to reproduce this issue, and at present, I'm using this module smoothly :-)
