### ISSUE TITLE
Upgrade from 1.1.2

### ISSUE THREAD

**Issue by brusilva84** [Icinga/icingaweb2-module-x509#182]
I've installed 1.1.2 from source and want to update to latest version.

I've tryed to clone the repo again but I get an error when running a job
Fatal error: Uncaught PDOException: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1685984017000' for column `x509`.`x509_job_run`.`start_time` at row 1 in /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php:402

Is there any SQL script to update the schema of the DB ?

**Comment by sukhwinder33445** [comment]
Hi @brusilva84,

yes, there is an upgrade file. You can find it [here](https://github.com/Icinga/icingaweb2-module-x509/tree/main/schema/mysql-upgrades).
