### ISSUE TITLE
Error message "Unable to locate monitoring module"

### ISSUE THREAD

**Issue by jprusch** [Icinga/icingaweb2-module-x509#187]
## Environment

Icinga Web 2 Version	2.11.4
Git Commit	11453bfa92a70a44efbf7f966f5e7f27e9300a28
PHP-Version	7.4.33
Git Commit Datum 2023-01-26

Geladene Bibliotheken
icinga/icinga-php-library	    0.12.0
icinga/icinga-php-thirdparty	0.11.0

Geladene Module
audit		    1.0.2	
businessprocess	2.4.0	
director		master	
doc		        2.11.4	
grafana		    2.0.3	
icingadb		1.0.2	
incubator		0.20.0	
jira		    1.3.0	
migrate		    2.11.4	
trapdirector	1.0.7a	
vspheredb	    1.7.1	
x509		    1.2.1

## Expected behaviour
Command should be executed & no error message should be printed, as the monitoring module is not listed as mandatory of x509

## Example
icinga@monhost:/var/log/icingaweb2# systemctl status icinga-x509.service
● icinga-x509.service - Icinga Certificate Monitoring Module Jobs Runner
     Loaded: loaded (/etc/systemd/system/icinga-x509.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2023-06-27 12:11:45 CEST; 3min 0s ago
   Main PID: 2414811 (icingacli)
      Tasks: 1 (limit: 18654)
     Memory: 11.0M
     CGroup: /system.slice/icinga-x509.service
             └─2414811 /usr/bin/php /usr/bin/icingacli x509 jobs run

Jun 27 12:11:45 monhost systemd[1]: Started Icinga Certificate Monitoring Module Jobs Runner.
Jun 27 12:11:45 monhost icingacli[2414811]: Unable to locate monitoring module

Also /var/log/icingaweb2/icingaweb2.log

2023-06-27T12:25:00+02:00 - ERROR - Unable to locate monitoring module
2023-06-27T12:25:00+02:00 - ERROR - Unable to locate monitoring module
2023-06-27T12:25:00+02:00 - ERROR - Unable to locate monitoring module
2023-06-27T12:25:00+02:00 - ERROR - Unable to locate monitoring module
2023-06-27T12:25:00+02:00 - ERROR - Unable to locate monitoring module
2023-06-27T12:25:00+02:00 - ERROR - Unable to locate monitoring module
2023-06-27T12:25:00+02:00 - ERROR - Unable to locate monitoring module

## Additional context
The monitoring module messes up with the new icingadb-web module. I didn't find any reference that the x509 module requires the monitoring module

**Comment by jprusch** [comment]
I reinstalled icingaweb2 with the monitoring module & disabled it. This solves the issue.

**Comment by yhabteab** [comment]
Hii @jprusch, thanks for reporting. Though, such an error log shouldn't prevent the x509 service from working.

> Active: active (running) since Tue 2023-06-27 12:11:45 CEST; 3min 0s ago

It also keeps running, as you can see in the systemd status output. The error logs originate actually from Icinga DB Web and not from the x509 module, but since they all share the same logger, **systemd** shows you this output. Icinga DB Web is still trying to load some classes/interfaces from the monitoring module to support some legacy hooks that I'm not aware of, but if you don't have problems with some hooks, you don't need to install the monitoring module and can safely ignore the error logs.

**Comment by jprusch** [comment]
Thx, I thought so.
