### ISSUE TITLE
Scan does not remove a deactivated SSL server 

### ISSUE THREAD

**Issue by Tuxdiver** [Icinga/icingaweb2-module-x509#21]
I deactivated some ssl webservers, but a new scan does not remove them from the module's database

## Expected Behavior
Scan should remove old entries

## Current Behavior
Scan does NOT remove old entries

## Possible Solution
Make it so!

## Steps to Reproduce (for bugs)
- Scan for SSL hosts
- deactivate Host (ifdown IP)
- Scan again
- Host still in x509 module list

## Your Environment

* Module version (System - About): git master a384a295a245cce32a2c754ab49557946350cd0d
* Icinga Web 2 version and modules (System - About): 2.6.1
* Icinga 2 version (`icinga2 --version`):  r2.10.2-1
* Operating System and version: Ubuntu 16.04

**Comment by Napsty** [comment]
Or (as a workaround) add a checkbox or drop-down menu to manually delete a certificate from the module database.

**Comment by Al2Klimov** [comment]
Hello @Tuxdiver and thank you for reporting!

Please could you test #31?

Best,
AK

**Comment by Tuxdiver** [comment]
Certificates are removed in "Certificate Usage" but not in "Certificate Overview".
I even find expired "lets encrypt" certs there.

Is that a bug or a feature?

**Comment by nilmerg** [comment]
@Tuxdiver Sorry for just closing this. I forgot to answer your question first..

Anyway, it's a feature. The overview is meant as some sort of inventory for certificates. Once collected they're kept at first. Though, it's for sure required to allow cleaning up legacy certificates there. There will be a separate issue for this.
