### ISSUE TITLE
Report expired status in CLI but not module interface

### ISSUE THREAD

**Issue by tete2soja** [Icinga/icingaweb2-module-x509#211]
## Describe the bug

Certificates show has expired on icingacli/icingaweb but not on module interface

## To Reproduce

I think it was working fine before general Debian update. But now, Even if the certification is showing correct information en Web interface (`Certificate chain is valid.` / `in 89 days`), the cli and icingaweb (since it uses the cli), shows error:

```
# icingacli x509 check host --host 'domain.tld'
CRITICAL - *.domain.tld has expired since 743 days|'*.domain.tld'=0s;16070400:;6393600:;0;-64215390
```

Maybe related with wildcard certificates but it was working fine before.

## Expected behavior

Show current status and not trigger warning/error status.

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 1.2.1
* Web browser used: Firefox
* Icinga 2 version used (`icinga2 --version`): r2.14.0-1
* PHP version used (`php --version`): php8.2
* Server operating system and version: Debian 12

**Comment by tete2soja** [comment]
Delete the database and import back the DDL and run the job seems to fix the issue.

**Comment by sdaru** [comment]
i have same issue 

- Icinga Web 2 version and modules (System - About): 2.10.5
- Web browser used: Firefox
- Icinga 2 version used (icinga2 --version): r2.14.0-1
- PHP version used (php --version):  7.4.33 
- Server operating system and version:  Red Hat Enterprise Linux release 8.9 (Ootpa)

Can someone help me ?

**Comment by nilmerg** [comment]
Have you tried what has been suggested previously?

**Comment by sdaru** [comment]
Yes i just do it:
Drop Database.
Recreate.
Import CA.
But still that error.

Kind Regards.
