### ISSUE TITLE
FeatureRequest / having the SNI somewhere related to the cidrs

### ISSUE THREAD

**Issue by moreamazingnick** [Icinga/icingaweb2-module-x509#213]
## Is your feature request related to a problem? Please describe.
The SNI mapping is now very far away from the job configuration.
It would be nice to get all matching snis for each job

## Describe the solution you'd like

<img width="681" alt="Screenshot 2023-10-20 004324" src="https://github.com/Icinga/icingaweb2-module-x509/assets/29682206/5b1b62ca-29ab-4884-bd32-aef0ee470a75">

<img width="680" alt="Screenshot 2023-10-20 004604" src="https://github.com/Icinga/icingaweb2-module-x509/assets/29682206/bab4b60d-68bc-4aff-93a8-29848aa21150">

**Comment by moreamazingnick** [comment]
#214

**Comment by yhabteab** [comment]
Hii @moreamazingnick, thanks for reporting!

> It would be nice to get all matching snis for each job

I wouldn't do that. I would simply move the `SNI` next to the `Jobs` tab just like it was before.
