### ISSUE TITLE
icingacli x509 jobs run fails with: Call to undefined method nextTick()

### ISSUE THREAD

**Issue by slalomsk8er** [Icinga/icingaweb2-module-x509#22]
## Expected Behavior
Following the documentation to create a `systemd` service results in working x509 jobs.

## Current Behavior
`icingacli x509 jobs run` fails with the following error message but `sudo -u www-data icingacli x509 scan --job self` works.
```
sudo -u www-data icingacli x509 jobs run
PHP Fatal error:  Uncaught Error: Call to undefined method React\EventLoop\StreamSelectLoop::nextTick() in /usr/share/icingaweb2/modules/x509/library/X509/Scheduler.php:30
Stack trace:
#0 /usr/share/icingaweb2/modules/x509/application/clicommands/JobsCommand.php(64): Icinga\Module\X509\Scheduler->add('self', '* * * * *', Object(Closure))
#1 /usr/share/php/Icinga/Cli/Loader.php(265): Icinga\Module\X509\Clicommands\JobsCommand->runAction()
#2 /usr/share/php/Icinga/Application/Cli.php(149): Icinga\Cli\Loader->dispatch()
#3 /usr/share/php/Icinga/Application/Cli.php(139): Icinga\Application\Cli->dispatchOnce()
#4 /usr/bin/icingacli(7): Icinga\Application\Cli->dispatch()
#5 {main}
  thrown in /usr/share/icingaweb2/modules/x509/library/X509/Scheduler.php on line 30

Fatal error: Uncaught Error: Call to undefined method React\EventLoop\StreamSelectLoop::nextTick() in /usr/share/icingaweb2/modules/x509/library/X509/Scheduler.php:30
Stack trace:
#0 /usr/share/icingaweb2/modules/x509/application/clicommands/JobsCommand.php(64): Icinga\Module\X509\Scheduler->add('self', '* * * * *', Object(Closure))
#1 /usr/share/php/Icinga/Cli/Loader.php(265): Icinga\Module\X509\Clicommands\JobsCommand->runAction()
#2 /usr/share/php/Icinga/Application/Cli.php(149): Icinga\Cli\Loader->dispatch()
#3 /usr/share/php/Icinga/Application/Cli.php(139): Icinga\Application\Cli->dispatchOnce()
#4 /usr/bin/icingacli(7): Icinga\Application\Cli->dispatch()
#5 {main}
  thrown in /usr/share/icingaweb2/modules/x509/library/X509/Scheduler.php on line 30

```

## Steps to Reproduce (for bugs)

1. create job 

option | value
-- | --
name | self
CIDRs | 127.0.0.1/30
Ports | 443
Scheduling | * * * * *

2. follow instructions to activate `systemd` service

## Your Environment

* Module version (System - About): 

Name | Version
-- | --
businessprocess | 2.1.0
cube | 1.0.1
director | master
doc | 2.6.2
generictts | 2.0.0
graphite | 1.1.0
incubator | v0.1.1
ipl | v0.1.1
monitoring | 2.6.2
reactbundle | v0.4.1
vspheredb | 1.0.3
x509 | 1.0.0

* Icinga Web 2 version and modules (System - About): 2.6.2
* Icinga 2 version (`icinga2 --version`): r2.10.2-1
* Operating System and version: Debian GNU/Linux 9.6
* Webserver, PHP versions: 7.0.30-0+deb9u1

**Comment by lippserd** [comment]
Hi,

Thanks for the report. I can confirm this. Will be fixed in a second.

Best,
Eric
