### ISSUE TITLE
Unable to filter for Expired Certificates within a given threshold from the Web Interface

### ISSUE THREAD

**Issue by gettoknowmii** [Icinga/icingaweb2-module-x509#233]
## Describe the bug
Previously i was able to list expired certificates from the web interface. However, after upgrading to the last x509 module. It no longer works. I am unable to list expired certificates from the web interface. The field does not even exists. Please see screenshots. 

## To Reproduce
Assuming you have icinga,icingaweb and x509 module installed and configure. Navigate to https://$URL/icingaweb2/x509/usage
Try filtering for certificates that will expired in 30 days from the search filter bar. The field 'Expire' or 'Expiration' does not even exist

<img width="385" alt="image" src="https://github.com/Icinga/icingaweb2-module-x509/assets/84911898/4ca9c17f-32a2-48a7-a719-af6c21e228be">

**Comment by yhabteab** [comment]
Hii @gettoknowmii, thanks for reporting!

The `expires` column was just an alias for `valid_to - valid_from` and we have dropped this in [`1.2.0`](https://icinga.com/docs/icinga-certificate-monitoring/latest/doc/80-Upgrading/#upgrading-to-version-120) as you can just use `valid_to` instead.

**Comment by gettoknowmii** [comment]
How can i used those two fields to get all certificates that will expired within 30 days. the query filter parameters would be really helpful.

**Comment by gettoknowmii** [comment]
I need a query using the valid_to - valid_from field to list all expired certs within 30 days

**Comment by slalomsk8er** [comment]
> How can i used those two fields to get all certificates that will expired within 30 days. the query filter parameters would be really helpful.
I don't think valid_from is needed if you need to get certs that expire in the next 30 days.
For me this URI worked:
`/icingaweb2/x509/usage?certificate.valid_to<1710425865&certificate.valid_to>1707920265`

**Comment by yhabteab** [comment]
There is also another expression column called `duration` (this is not a database column, but just an alias for `valid_to -valid_from` like the former column `expires`, but it is created when generating the query like `(valid_to - valid_from) as duration`).

<img width="765" alt="Bildschirmfoto 2024-02-15 um 09 43 28" src="https://github.com/Icinga/icingaweb2-module-x509/assets/57616252/9cde0ef8-82c4-49a6-a2f4-50a327bec1e9">

**Comment by nilmerg** [comment]
`/icingaweb2/x509/certificates?certificate.valid_to>now&certificate.valid_to<30days` should also work.

**Comment by gettoknowmii** [comment]
Awesome thank you
