### ISSUE TITLE
Binary files in upstream (*.png) for debian package.

### ISSUE THREAD

**Issue by daku69** [Icinga/icingaweb2-module-x509#235]
## Describe the bug
In doc/res/ exist some *.png files. In debian it is not allowed to import binary files without source code.

To by confirm with the policis it is enough to include a file like .xcf.

Thanks you for your feedback.

**Comment by slalomsk8er** [comment]
Feel free to fork the repository, open the PNGs in GIMP, save the XCFs besides the PNGs, and create a pull request ;)

**Comment by daku69** [comment]
thanks for the quick reply.
