### ISSUE TITLE
Sorting based on expiration time

### ISSUE THREAD

**Issue by ChristianMoritz** [Icinga/icingaweb2-module-x509#24]
I think this could be a good feature reuquest.

Is there an option to add the ability to make the rows (certificate, issuer, Signature Algorithm, Public Key & Expires) sortable or better to select the row's which should be shown in the "Certificate Overview". this will be realy good. 

f.e. 
my security admin only needs an dashboard with the certificates which expire within the next 90 days. and for this only the FQDN from the certificate, signature algorythm & the time left to extend the certificate.

**Comment by ChristianMoritz** [comment]
ive updated all modules...
during this i updated the x509 module...

now it works (y)

**Comment by nilmerg** [comment]
Are you sure you've meant to close this issue and not #25? Because this one is a reasonable feature request :grin:
