### ISSUE TITLE
Error on CA-Import

### ISSUE THREAD

**Issue by hensschenit** [Icinga/icingaweb2-module-x509#26]
Hi!

I'm trying to get the x509-module to work. 
Installation works fine, so database schema is imported and the module was activated in incingaweb2.

So when i try to import a CA, for example Let's Encrypt X3, then i get the following error:
```
PHP Fatal error:  Uncaught Error: Call to undefined method Icinga\Module\X509\Clicommands\ImportCommand::getModuleName() in /usr/share/icingaweb2/modules/x509/library/X509/Command.php:18
Stack trace:
#0 /usr/share/php/Icinga/Cli/Loader.php(264): Icinga\Module\X509\Command->init()
#1 /usr/share/php/Icinga/Application/Cli.php(150): Icinga\Cli\Loader->dispatch()
#2 /usr/share/php/Icinga/Application/Cli.php(139): Icinga\Application\Cli->dispatchOnce()
#3 /usr/bin/icingacli(7): Icinga\Application\Cli->dispatch()
#4 {main}
  thrown in /usr/share/icingaweb2/modules/x509/library/X509/Command.php on line 18

Fatal error: Uncaught Error: Call to undefined method Icinga\Module\X509\Clicommands\ImportCommand::getModuleName() in /usr/share/icingaweb2/modules/x509/library/X509/Command.php:18
Stack trace:
#0 /usr/share/php/Icinga/Cli/Loader.php(264): Icinga\Module\X509\Command->init()
#1 /usr/share/php/Icinga/Application/Cli.php(150): Icinga\Cli\Loader->dispatch()
#2 /usr/share/php/Icinga/Application/Cli.php(139): Icinga\Application\Cli->dispatchOnce()
#3 /usr/bin/icingacli(7): Icinga\Application\Cli->dispatch()
#4 {main}
  thrown in /usr/share/icingaweb2/modules/x509/library/X509/Command.php on line 18
```

Command: `icingacli x509 import --file /home/user123/downloads/letsencryptauthorityx3.pem `

Does anyone have a solution for me, please?

Environment:
Icinga2 -> v2.6.0
IcingaWeb2 -> v2.6.2 (just updated)
ipl-module -> v0.1.1
reactbundle-module -> v0.4.1
php7.0-gmp -> 7.0.30-0+deb9u1 (via official Debian repo)
php -> 7.0.30-0+deb9u1

Thank's! Tommy

**Comment by Jazb** [comment]
Same error, trying to import default CA certificates of CentOS distro

The command: 

 icingacli x509 import --file /etc/ssl/certs/ca-bundle.crt

In my case the fix was: 

yum install rh-php71-php-gmp ### Install the dependencies list on documentation
scl enable rh-php71 bash ### Start a shell with right version of php of my environment

I'am expect to help you

**Comment by hensschenit** [comment]
@Jazb: Thank's for your reply.
But as it seems is `rh-php71-php-gmp` a specific package for CentOS.
So i can't find it in my repos for Debian.

Any other suggestions?

**Comment by Al2Klimov** [comment]
Hello @hensschenit and thank you for your interest in this module!

Fortunately that package isn't CentOS-specific, it's just named "the Debian way" in Debian.

Best,
AK

```
root@8b13c56e5433:/# apt search php.\*gmp
Sorting... Done
Full Text Search... Done
php-gmp/stable 1:7.0+49 all
  GMP module for PHP [default]

php7.0-gmp/stable 7.0.33-0+deb9u1 amd64
  GMP module for PHP

root@8b13c56e5433:/#
```

**Comment by nilmerg** [comment]
Are you sure you've installed the correct version of Icinga Web 2?

The error above may occur with versions lower than 2.4.2 but shouldn't with newer ones. Though, the module already requires at least v2.5.

I'll close this now, but if you still have problems don't hesitate to report back.
