### ISSUE TITLE
Can't import mysql.schema.sql

### ISSUE THREAD

**Issue by kevinstiller** [Icinga/icingaweb2-module-x509#3]
Importing with "mysql -p -u root x509 < etc/schema/mysql.schema.sql"

Error:
ERROR 1071 (42000) at line 50: Specified key was too long; max key length is 767 bytes

MySQL:
mysql  Ver 15.1 Distrib 5.5.60-MariaDB, for Linux (x86_64) using readline 5.1

CentOS 7, fully patches
Everything Up2Date incl. PHP 7.x

**Comment by trendchiller** [comment]
You have to edit your database config file and add a few lines, e.g.

sudo vi /etc/mysql/mariadb.conf.d/50-server.cnf
 ADD
 innodb_file_format=barracuda
 innodb_file_per_table=1
 innodb_large_prefix=1

reboot your database server

 mysql -u root -p x509 < etc/schema/mysql.schema.sql

**Comment by kevinstiller** [comment]
CentOS 7: vi /etc/my.cnf.d/server.cnf

Missread the MySQL Version at first. My bad!

**Comment by lippserd** [comment]
Thanks for your help @trendchiller. I'll close this one.

**Comment by lippserd** [comment]
@trendchiller @kevinstiller Don't forget to star this module (if you like it 😆)

**Comment by jorge-rodr** [comment]
mysql -p -u root x509 < **/**etc/schema/mysql.schema.sql

The slash was missing in the documentation.
