### ISSUE TITLE
Base table or view not found: 1146 Table 'x509.x509_certificate' doesn't exist

### ISSUE THREAD

**Issue by FiggyRoll** [Icinga/icingaweb2-module-x509#36]
## Expected Behavior
Module configuration available when choosing x509 tab in Icinga Web 2

## Current Behavior
Follow the step by step guide to install the module, then when I select the x509 module to start using it, i get the following error

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'x509.x509_certificate' doesn't exist

and

STATE[42S02]: Base table or view not found: 1146 Table 'x509.x509_target' doesn't exist

## Your Environment

* Module version (System - About):
    1.0.0

* Icinga Web 2 version and modules (System - About):
    2.6.1

* Icinga 2 version (`icinga2 --version`):
    icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.0-1)

* Operating System and version:
    Platform: Red Hat Enterprise Linux Server
  Platform version: 7.4 (Maipo)
  Kernel: Linux
  Kernel version: 3.10.0-693.11.6.el7.x86_64
  Architecture: x86_64

* Webserver, PHP versions:
    PHP 5.4.16

**Comment by nilmerg** [comment]
Hi,

the installation documentation clearly states that the database setup is required prior to enabling the module. Since said database setup includes instructions to import the schema (which you seem to have skipped) this issue you're reporting should not occur.

**Comment by FiggyRoll** [comment]
HI @nilmerg 

Thanks for the response, I havnt skipped importing the schema. I did perform that step, im not sure why you have assumed that I have skipped that step?

Thanks

**Comment by nilmerg** [comment]
Because the error message talks about a missing table, which is part of the schema. The name of the database is neither wrong (otherwise the error message would be a different one) nor is the table name. The resource also exists, otherwise you wouldn't have come this far to see this error. So my conclusion is that by doing the entire database setup, prior even accessing the module within Icinga Web 2, does not lead to such an error.

You may not have skipped the import, but it certainly wasn't successful. If it is done at the proposed stage and successful the module works perfectly.

**Comment by FiggyRoll** [comment]
So all thats fair enough, but I did state that I have followed the step by step guide to install the module, of which the very first steps are configuring the database. 

So I did perform that step at the stage the guide says to do this, and no error was given, but clearly wasn't successful, is there any troubleshooting I can perform to see why the import wasn't successful?

Thanks

**Comment by nilmerg** [comment]
If it wasn't successful there would have been an error occurred and reported. For further questions about troubleshooting this please head over to our forums: https://community.icinga.com

**Comment by sarojamarraj** [comment]
Even I'm facing a similar issue after following each and every step mentioned in the installation part.
The schema was imported successfully just after the databases x509 was created. 
Here's the table view of x509 DB:-
mysql> show tables;
+----------------------------+
| Tables_in_x509             |
+----------------------------+
| icingaweb_group            |
| icingaweb_group_membership |
| icingaweb_user             |
| icingaweb_user_preference  |
+----------------------------+
4 rows in set (0.00 sec) 

Any solution on this ?

**Comment by nilmerg** [comment]
The tables you are showing are those of Icinga Web2 itself. You've definitely configured the wrong resource in the module configuration.

**Comment by sarojamarraj** [comment]
Here is the resource configuration, 
![image](https://user-images.githubusercontent.com/35187689/72142782-76028900-33bb-11ea-952b-4a52f8c67e16.png)

and here is the backend configuration for module x509
![image](https://user-images.githubusercontent.com/35187689/72142827-93cfee00-33bb-11ea-9849-e460ba7bffdc.png)

I think i have correctly followed the steps, infact i tried doing it several times but no success, 
thanks for replying quickly.

**Comment by nilmerg** [comment]
The configuration seems to be correct. But the tables are still those of Icinga Web 2. Are you sure you've imported the schema of the module?

**Comment by sarojamarraj** [comment]
Yes i'm sure, i think this will help you, as you can see i didn't get any error after importing schema.

root@hawkeye:/usr/share/icingaweb2# mysql -p -u root x509 < etc/schema/mysql.schema.sql
Enter password:
root@hawkeye:/usr/share/icingaweb2# cd modules/
root@hawkeye:/usr/share/icingaweb2/modules# git clone https://github.com/Icinga/icingaweb2-module-x509.git x509
Cloning into 'x509'...
remote: Enumerating objects: 1605, done.
remote: Total 1605 (delta 0), reused 0 (delta 0), pack-reused 1605
Receiving objects: 100% (1605/1605), 922.63 KiB | 0 bytes/s, done.
Resolving deltas: 100% (798/798), done.
Checking connectivity... done.
root@hawkeye:/usr/share/icingaweb2/modules# ll
total 64
drwxr-xr-x 16 root root 4096 Jan 10 10:06 ./
drwxr-xr-x  9 root root 4096 Jan 21  2019 ../
drwxr-xr-x 11 root root 4096 Jan 21  2019 director/
drwxr-xr-x  6 root root 4096 Nov 25 10:00 doc/
drwxr-xr-x  5 root root 4096 Jun 25  2019 idoreports/
drwxr-xr-x  4 root root 4096 Jun 14  2019 ipl/
drwxr-xr-x  4 root root 4096 Nov 25 10:00 migrate/
drwxr-xr-x  7 root root 4096 Nov 25 10:00 monitoring/
drwxr-xr-x  5 root root 4096 Jun 14  2019 pdfexport/
drwxr-xr-x  4 root root 4096 Jun 14  2019 reactbundle/
drwxr-xr-x  9 root root 4096 Jun 14  2019 reporting/
drwxr-xr-x  5 root root 4096 Nov 25 10:00 setup/
drwxr-xr-x  3 root root 4096 Nov 25 10:00 test/
drwxr-xr-x  5 root root 4096 Nov 25 10:00 translation/
drwxr-xr-x  6 root root 4096 Jan 21  2019 vsphere/
drwxr-xr-x 11 root root 4096 Jan 10 10:06 x509/

**Comment by nilmerg** [comment]
That's the culprit:
> root@hawkeye:/usr/share/icingaweb2# mysql -p -u root x509 < etc/schema/mysql.schema.sql

That should be:
> root@hawkeye:/usr/share/icingaweb2/modules/x509# mysql -p -u root x509 < etc/schema/mysql.schema.sql

**Comment by sarojamarraj** [comment]
Hey, thanks :-) 

It worked now, I misunderstood the document may be because the step of importing schema is before cloning the module under Icinga Web 2 module path.

In reality, it worked as you said to import the schema from the file which is under cloned x509 module.
