### ISSUE TITLE
How to remove CA certs from store

### ISSUE THREAD

**Issue by trendchiller** [Icinga/icingaweb2-module-x509#4]
How can we remove imported CA-creeps from the store ?
Is there a cli or is it better using mysql commands ?

**Comment by lippserd** [comment]
Hi,

The module is missing CLI commands and GUI actions for managing your certificate store. At the moment, your only choice is to use MySQL commands.

Best,
Eric

**Comment by lippserd** [comment]
I'll open a feature request later on.

**Comment by trendchiller** [comment]
Ok, got it, do you have a hint for me where to look for the CA-certs in MySQL ?

**Comment by Al2Klimov** [comment]
@lippserd What about replacing the (present and absent) thumbs up in the certificates table with checkboxes – just for the self-signed CAs?

**Comment by trendchiller** [comment]
Got it, thank you ;-)

Am 29.11.2018 um 13:06 schrieb Eric Lippmann <notifications@github.com<mailto:notifications@github.com>>:


Hi,

The table you're looking for is x509_certificate. If you want to have a look at all your imported CAs you may run:

SELECT * FROM x509_certificate WHERE ca = 'yes'\G

I may help you with query further if you tell me which CAs you want to remove or how we could identify them, e.g. by subject or issuer or whatever.

Best,
Eric
