### ISSUE TITLE
SQLSTATE[22003]: Numeric value out of range:

### ISSUE THREAD

**Issue by TobiasKneidl** [Icinga/icingaweb2-module-x509#43]
## Current Behavior
If I try to scan port 43586, an SQL error occured:

`SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'port' at row 1
#0 /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(315): PDOStatement >execute(Array)
#1 /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(351): ipl\Sql\Connection->prepexec('INSERT INTO x50...')
#2 /usr/share/icingaweb2/modules/x509/library/X509/Job.php(213): ipl\Sql\Connection->insert('x509_target', Array)
#3 [internal function]: Icinga\Module\X509\Job->Icinga\Module\X509\{closure}(Object(ipl\Sql\Connection))
#4 /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(452): call_user_func(Object(Closure), Object(ipl\Sql\Connection))
#5 /usr/share/icingaweb2/modules/x509/library/X509/Job.php(289): ipl\Sql\Connection->transaction(Object(Closure))
#6 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/FulfilledPromise.php(25): Icinga\Module\X509\Job->Icinga\Module\X509\{closure}(Object(React\Socket\Connection))
#7 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then(Object(Closure), Object(Closure))
#8 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#9 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#10 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/FulfilledPromise.php(39): React\Promise\Promise::React\Promise\{closure}(Object(React\Socket\Connection))
#11 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(135): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure), Object(Closure))
#12 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#13 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#14 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise-timer/src/functions.php(31): React\Promise\Promise::React\Promise\{closure}(Object(React\Socket\Connection))
#15 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/FulfilledPromise.php(25): React\Promise\Timer\{closure}(Object(React\Socket\Connection))
#16 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then(Object(Closure), Object(Closure))
#17 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#18 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#19 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/FulfilledPromise.php(25): React\Promise\Promise::React\Promise\{closure}(Object(React\Socket\Connection))
#20 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then(Object(Closure), Object(Closure))
#21 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#22 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#23 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/FulfilledPromise.php(39): React\Promise\Promise::React\Promise\{closure}(Object(React\Socket\Connection))
#24 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(66): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure))
#25 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#26 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#27 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/FulfilledPromise.php(39): React\Promise\Promise::React\Promise\{closure}(Object(React\Socket\Connection))
#28 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(135): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure), Object(Closure))
#29 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#30 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#31 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/FulfilledPromise.php(39): React\Promise\Promise::React\Promise\{closure}(Object(React\Socket\Connection))
#32 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(135): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure), Object(Closure))
#33 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#34 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#35 /usr/share/icingaweb2/modules/reactbundle/vendor/react/promise/src/Deferred.php(36): React\Promise\Promise::React\Promise\{closure}(NULL)
#36 /usr/share/icingaweb2/modules/reactbundle/vendor/react/socket/src/StreamEncryption.php(123): React\Promise\Deferred->resolve()
#37 /usr/share/icingaweb2/modules/reactbundle/vendor/react/socket/src/StreamEncryption.php(81): React\Socket\StreamEncryption->toggleCrypto(Resource id #6154, Object(React\Promise\Deferred), true, 57)
#38 /usr/share/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/StreamSelectLoop.php(244): React\Socket\StreamEncryption->React\Socket\{closure}(Resource id #6154)
#39 /usr/share/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/StreamSelectLoop.php(211): React\EventLoop\StreamSelectLoop->waitForStreamActivity(2285360)
#40 /usr/share/icingaweb2/modules/x509/library/X509/Job.php(349): React\EventLoop\StreamSelectLoop->run()
#41 /usr/share/icingaweb2/modules/x509/application/clicommands/ScanCommand.php(50): Icinga\Module\X509\Job->run()
#42 /usr/share/php/Icinga/Cli/Loader.php(265): Icinga\Module\X509\Clicommands\ScanCommand->indexAction()
#43 /usr/share/php/Icinga/Application/Cli.php(149): Icinga\Cli\Loader->dispatch()
#44 /usr/share/php/Icinga/Application/Cli.php(139): Icinga\Application\Cli->dispatchOnce()
#45 /usr/bin/icingacli(7): Icinga\Application\Cli->dispatch()
#46 {main}`

**Comment by nilmerg** [comment]
Hi, thanks for the report!

This is a bug in the database schema. You may fix this by applying the following to the database:

```sql
ALTER TABLE x509_target MODIFY COLUMN `port` smallint unsigned NOT NULL;
```

**Comment by TobiasKneidl** [comment]
Works, thanks!
