### ISSUE TITLE
Provide a widget to define job schedules with

### ISSUE THREAD

**Issue by JulGiul** [Icinga/icingaweb2-module-x509#46]
Which are the correct entries for JOB SCHEDULE field ?

## Expected Behavior
Suggest the correct values for this field

## Current Behavior
It is a free text filed: no choices are preconfigured

## Possible Solution
Please document what this field is needed for, including correct values to type in.
Or make availeble a choice list

## Steps to Reproduce (for bugs)
1. go to "create a now job"
2. in the right pane, click on the right of the word Schedule
3. write whatever you want
4. what is it needed for ??

## Your Environment
New Icinga installation - it is a lack of information, not a configuration specific bug.

![IcingaX509Job](https://user-images.githubusercontent.com/50139793/56958640-1759ef80-6b4b-11e9-963b-77dec80e4c40.PNG)

**Comment by nilmerg** [comment]
Hi,

documentation about this can be found [here](https://github.com/Icinga/icingaweb2-module-x509/blob/master/doc/03-Configuration.md#scheduling-jobs).

Though, you're right that being this a free text field is not optimal. This may even be easily transformed into a widget. Might be a candidate for the next release. :+1:

**Comment by flourish86** [comment]
To make the selection dropdown clearer, separate the options. You can do this with wrapping `<options>` im `<optgroup>` elements. A `label` attribute sets a title for the section.
![Desktop Copy](https://user-images.githubusercontent.com/6977434/201093496-6cf67de1-1a5d-4ccb-a010-f8cda5d489c1.jpg)

We should also have an additional Element, that predicts at least the next occurrence
![Desktop Copy 3](https://user-images.githubusercontent.com/6977434/201094005-27428ac6-97ab-4f17-9ac3-67ea6cace8df.jpg)

Custom Weekly
![Custom Weekly](https://user-images.githubusercontent.com/6977434/201094649-3b05a489-8190-4b29-bf68-6da7da11fb6b.jpg)

Custom Monthly
![Custom Monthly](https://user-images.githubusercontent.com/6977434/201094680-b228076d-708c-4f3c-9bb7-dbe4aeaf1d77.jpg)

Custom Annually
![Custom Annually](https://user-images.githubusercontent.com/6977434/201094700-3c77fd4a-f9d3-4c51-a40f-c45521b212cd.jpg)

Additionally we should have an "End Repeat" Field as well
![Desktop Copy 17](https://user-images.githubusercontent.com/6977434/201094977-1088b6b9-4f70-4f77-87e1-013246047e17.jpg)
