### ISSUE TITLE
List of hosts/ips + port where cert was found

### ISSUE THREAD

**Issue by Gninieb** [Icinga/icingaweb2-module-x509#48]
It would be great if we see where the cert was found respectively how often it was found. 
Maybe a count how often it was found as button to open a new tab where we see a chart with IP + Port where the cert was found. Maybe add scantime to the list to get historical data.

scantime/job-name - ip - port

**Comment by nilmerg** [comment]
Hi, this is already covered by #41. Though, please add a comment there about the time when the certificate has been registered, so that this doesn't get lost.
