### ISSUE TITLE
Allow deleting of removed hosts

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2-module-x509#58]
Please add a button to delete hosts / certificates which are no longer in use. It's good that they are not removed automatically but sometimes hosts get removed from the infrastructure and it would really help if they could be remove from the module, too.

This was already mentioned in #21

**Comment by widhalmt** [comment]
ref/NC/624641

**Comment by nilmerg** [comment]
You were absolutely right putting this in #40. So why a new issue?

**Comment by widhalmt** [comment]
I thought #40 was about removing historical data from a host that still exists. This issue is about completely removing a host from the database.

**Comment by nilmerg** [comment]
Nope, that's exactly what #40 is about. Just the note about the button to purge the data has been forgotten since #21. Which you now provided. :wink:
