### ISSUE TITLE
Missing class ipl/Sql

### ISSUE THREAD

**Issue by iDemonix** [Icinga/icingaweb2-module-x509#6]
Hi, I have installed the module as per the instructions, but get the following error in the web UI:

```
Uncaught Error: Class 'ipl\Sql\Config' not found in /usr/share/icingaweb2/modules/x509/library/X509/Controller.php:24
Stack trace:
#0 /usr/share/icingaweb2/modules/x509/application/controllers/DashboardController.php(19): Icinga\Module\X509\Controller->getDb()
#1 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\X509\Controllers\DashboardController->indexAction()
#2 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('indexAction')
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#4 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#5 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#6 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#7 {main}
thrown
```

I tried to `composer require ipl\Sql` and I checked the lippserd repos, but I can't seem to find it?

**Comment by iDemonix** [comment]
Realised my pre-req Icinga2 IPL install didn't work, fixed that, working now.

Would be great if this could somehow be wrapped in to composer.

**Comment by lippserd** [comment]
Hi,

This module has two dependencies to other Icinga 2 modules:

* https://github.com/Icinga/icingaweb2-module-reactbundle
* https://github.com/Icinga/icingaweb2-module-ipl

Make sure to checkout the latest tag or use a release tarball for both modules.

Please give me a short ping here whether this fixes your isse.

Best,
Eric

**Comment by lippserd** [comment]
Ok, you were faster 😆

**Comment by sgrrr** [comment]
I just ran into the exact same error and I did install all three modules from tarball. 
Any ideas to resolve this apart from reinstalling (which I already did) would be appreciated ;)

**Comment by lippserd** [comment]
Hi,

`icingacli module list` should show something like `ipl v0.1.1 enabled The Icinga PHP library`. Is that true on your end as well?

Best,
Eric

**Comment by sgrrr** [comment]
Hi Eric, i got 0.2.0 but yes, it's listed

**Comment by lippserd** [comment]
Could you share the output of `icingacli module list --installed` please.

**Comment by sgrrr** [comment]
```
MODULE         VERSION   STATE     DESCRIPTION
doc            2.6.2     disabled  Documentation module
ipl            v0.2.0    enabled   The Icinga PHP library
migrate        2.6.2     disabled  Migrate module
monitoring     2.6.2     enabled   Icinga monitoring module
reactbundle    v0.5.1    enabled   ReactPHP-based 3rd party libraries
setup          2.6.2     disabled  Setup module
test           2.6.2     disabled  Translation module
translation    2.6.2     disabled  Translation module
x509           1.0.0     enabled   Scan and view X.509 certificate usage
```

**Comment by lippserd** [comment]
The Sql package is missing in the latest ipl module release 😆Give us some secs please.

**Comment by Thomas-Gelf** [comment]
@sgrrr: there was an error in the release-script, now there is v0.2.1 - and ipl\Sql should be back.
