### ISSUE TITLE
Dashboard fails to open: Numeric value out of range: 1690 BIGINT UNSIGNED value is out of range

### ISSUE THREAD

**Issue by yoogie27** [Icinga/icingaweb2-module-x509#60]
## Describe the bug
Opening the dashboard shows the following error:
SQLSTATE[22003]: Numeric value out of range: 1690 BIGINT UNSIGNED value is out of range in '(`x509`.`x509_certificate`.`valid_to` - `x509`.`x509_certificate`.`valid_from`)'

## Expected behavior
It should show the graphs with the certificate usage

## Your Environment
Running on Ubuntu 18.04 with MariaDB 10.0.38

* Icinga Web 2 version and modules (System - About): 2.6.2, IPL: 0.3.0
* Icinga 2 version used (`icinga2 --version`): 2.10.4
* PHP version used (`php --version`): 7.0.33
* Server operating system and version: Ubuntu 1804

## Additional context
I could resolve the issue by replacing every "valid_from" (in SQL queries) with "cast(valid_from as signed)" and every "valid_to" with "cast(valid_to as signed)"

## Stack trace
`#0 /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(315): PDOStatement->execute(Array)
#1 /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php(331): ipl\Sql\Connection->prepexec(String, Array)
#2 /usr/share/icingaweb2/modules/x509/application/controllers/DashboardController.php(58): ipl\Sql\Connection->select(Object(ipl\Sql\Select))
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\X509\Controllers\DashboardController->indexAction()
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#6 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#8 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#9 {main}`

**Comment by deikelenboom** [comment]
Related to this: 

For me, I was able to open the dashboard after install, but running a job from the icingacli resulted in the same error. Changing `valid_from` and `valid_to` to signed BIGINTs in the `x509_certificate` table fixed the issue.

In your case. it is probably related to the fact that you have an expired certificate, and an unsigned BIGINT cannot be less than 0.

**Comment by nilmerg** [comment]
This should actually not happen. `valid_from` is the starting time since when a certificate is valid. `valid_to` is the time when it ends being valid. (i.e. `valid_from` < `valid_to`) So subtracting `valid_from` from `valid_to` should not result in a value less than 0.

The reason why it's happening for you may be due to a faulty certificate which is never valid. (i.e. `valid_to` < `valid_from`) Or is this even a *valid* thing?
