### ISSUE TITLE
Validation does not evaluate the entire chain

### ISSUE THREAD

**Issue by flybyray** [Icinga/icingaweb2-module-x509#64]
## Describe the bug
The check will not show WARNING or CRITICAL if the server is presenting a full chain with
'remaining time of ca/intermediate less than leaf certificate'.

the following example is showing an example of the certificate usage in that case and reports 'OK - .... expires in 524 days'
![image](https://user-images.githubusercontent.com/804661/70536002-4a8f4300-1b5e-11ea-9d1f-32ed93dc8996.png)

## To Reproduce

import some certificate chain with specific data. essential example data is given below in the table in section 'Additional context'.

background: cross signing certificates often used to transform CAs. In such situations it might happen that more than one certificate path is possible.
For details see the current case with sectigo certificates: https://support.sectigo.com/Com_KnowledgeDetailPageFaq?Id=kA01N000000rgSZ

## Expected behavior
CheckCommand should evaluate the whole chain.

## Screenshots
this is shown in the description above:
![image](https://user-images.githubusercontent.com/804661/70536002-4a8f4300-1b5e-11ea-9d1f-32ed93dc8996.png)

## Your Environment
This is an implementation bug it will happen in any version i checked.

* Icinga Web 2 version and modules (System - About):
* Web browser used:
* Icinga 2 version used (`icinga2 --version`):
* PHP version used (`php --version`):
* Server operating system and version:

## Additional context

I modified the query from the check slightly to show case more insights of this problem.
```
SELECT c.id,
       t.port,
       cc.valid,
       cc.invalid_reason,
       c.subject,
       ci.self_signed as ci_ss,
       c.self_signed as c_ss,
       COALESCE(ci.self_signed, c.self_signed) as self_signed,
       c.valid_from,
       c.valid_to,
       ccl.`order`
FROM x509_target t
         JOIN x509_certificate_chain cc ON cc.id = t.latest_certificate_chain_id
         JOIN x509_certificate_chain_link ccl ON ccl.certificate_chain_id = cc.id
         JOIN x509_certificate c ON c.id = ccl.certificate_id
         LEFT JOIN x509_certificate ci ON ci.subject_hash = c.issuer_hash
WHERE t.hostname = 'hallo.mywildcard.com' and
      t.port = 443
ORDER BY ccl.`order` ASC;
```

| id | port | valid | invalid\_reason | subject | ci\_ss | c\_ss | self\_signed | valid\_from | valid\_to | order |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 40 | 443 | yes | NULL | \*.mywildcard.com | no | no | no | 1558137600 | 1621295999 | 0 |
| 10 | 443 | yes | NULL | Sectigo RSA Domain Validation Secure Server CA | no | no | no | 1541116800 | 1924991999 | 1 |
| 10 | 443 | yes | NULL | Sectigo RSA Domain Validation Secure Server CA | yes | no | yes | 1541116800 | 1924991999 | 1 |
| 41 | 443 | yes | NULL | USERTrust RSA Certification Authority | yes | no | yes | 959683718 | 1590835718 | 2 |
| 36 | 443 | yes | NULL | AddTrust External CA Root | yes | yes | yes | 959683718 | 1590835718 | 3 |

that shows some more droubles here with the `join` and maybe the 2 cert chain pathes 
see https://support.sectigo.com/Com_KnowledgeDetailPageFaq?Id=kA01N000000rgSZ

**Comment by Al2Klimov** [comment]
OK, this should generate a complex enough chain (for now):

```bash
openssl genrsa -out pusher.key 1024
openssl genrsa -out newcomer.key 1024
openssl genrsa -out 127.0.0.1.key 1024

openssl req -new -x509 -key pusher.key -subj '/CN=Pusher root CA' -days 100 -sha1 -out pusher.crt

openssl req -new -x509 -key newcomer.key -subj '/CN=Newcomer root CA' -days 300 -sha1 -out newcomer-root.crt

openssl req -new -key newcomer.key -subj '/CN=Newcomer root CA' -out newcomer-cs.csr
openssl x509 -req -in newcomer-cs.csr -sha1 -days 200 -out newcomer-cs.crt -CA pusher.crt -CAkey pusher.key -CAcreateserial -extensions ext -extfile <(printf '[ext]\nbasicConstraints=CA:TRUE,pathlen:0')

CN_KIND=IP ; CN=127.0.0.1
openssl req -new -key 127.0.0.1.key -subj "/CN=$CN" -out 127.0.0.1.csr
openssl x509 -req -in 127.0.0.1.csr -sha1 -days 400 -out 127.0.0.1.crt -CA newcomer-root.crt -CAkey newcomer.key -CAcreateserial -extensions SAN -extfile <(printf '[SAN]\nsubjectAltName=%s:%s' "$CN_KIND" "$CN")
```

The root CA newcomer-root.crt signs the leaf 127.0.0.1.crt and the root CA pusher.crt cross-signs newcomer-root.crt (newcomer-cs.crt).

```bash
openssl verify -CAfile newcomer-root.crt 127.0.0.1.crt
openssl verify -CAfile pusher.crt -untrusted newcomer-cs.crt 127.0.0.1.crt
```

127.0.0.1.crt has two possible paths.

**Comment by Al2Klimov** [comment]
And this should import it:

```bash
icingacli x509 import --file pusher.crt
icingacli x509 import --file newcomer-root.crt
icingacli x509 scan --job JOBNAME
```

The server behind JOBNAME should also serve the cross-signed intermediate, i.e.:

```bash
openssl s_server -key 127.0.0.1.key -cert 127.0.0.1.crt -CAfile newcomer-cs.crt
```

Yes, `-CAfile`. 🤷‍♂️

**Comment by Al2Klimov** [comment]
As far as I read the `Job#processChain()` callers (and the data in DB) they get their chai**n** (singular!) from PHP itself which likely gets it from libssl which chooses a chain path **for us**. (In my case: Newcomer Root -> Leaf) IMAO if I considered Newcomer Root not well-known enough yet to rely in my checks that clients have it in their trust stores, I had to remove it from mine, so that the next time libssl chooses Pusher -> Newcomer C/S -> Leaf. If I'm right on this, only one problem is left...

> the server is presenting a full chain with
> 'remaining time of ca/intermediate less than leaf certificate
