### ISSUE TITLE
Certificate verification fails with older OpenSSL versions

### ISSUE THREAD

**Issue by benhur1999** [Icinga/icingaweb2-module-x509#68]
## Describe the bug
Certificate verification fails with OpenSSL 1.0.2k-fips on CentOS 7.
Version 1.0.2 does not support multiple "-untrusted" arguments for the verify command.

## To Reproduce
1. Setup x509 module as described in the documentation on CentOS 7
2. Import CA certificates
3. Create a can job
4. Run the job and inspect results. For all certificates, the module states "Certificate chain is invalid: unable to get local issuer certificate."

## Expected behavior
Valid certificates with proper chain should be regared a valid.

## Your Environment
* OpenSSL 1.0.2k-fips

* Icinga Web 2 version and modules (System - About):
```
Icinga Web 2 Version
    2.7.3
Git commit
    06cabfe8ba28cf545a42c92f25484383191a4e51
PHP Version
    7.3.14
Git commit date
    2019-10-18
Name | Version
-- | --
doc | 2.7.3
grafana | 1.3.6
ipl | v0.3.0
monitoring | 2.7.3
reactbundle | 0.7.0
x509 | 1.0.0
```

* Web browser used:
`Firefox 72.0.2 (64bit) / Windows 10`

* Icinga 2 version used (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.11.2-1)

Copyright (c) 2012-2020 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-1062.12.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: buildhost.ids-mannheim.de

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```
* PHP version used (`php --version`): 
```
PHP 7.3.14 (cli) (built: Jan 21 2020 09:59:50) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.14, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.14, Copyright (c) 1999-2018, by Zend Technologies
```
* Server operating system and version:
 ` CentOS Linux release 7.7.1908`
  
* OpenSSL:
`OpenSSL 1.0.2k-fips  26 Jan 2017`

## Additional context
The man page for "verify" states:
> A file of untrusted certificates. The file should contain multiple
>  certificates in PEM format concatenated together.

For openssl version 1.1.1d (on FreeBSD FWIW) states:
>  A file of additional untrusted certificates (intermediate issuer CAs) used to construct a
> certificate chain from the subject certificate to a trust-anchor. The file should contain
> one or more certificates in PEM format. **This option can be specified more than
> once to include untrusted certificates from multiple files**.

Non-working invokation of openssl (multiple -untrusted):
```
$ openssl verify -verbose -CAfile ca5e3c3296e4415 -untrusted intermediate5e3c3296e4ae5 -untrusted intermediate5e3c3296e4ab1 -untrusted intermediate5e3c3296e4a60  cert5e3c3296e4a23
cert5e3c3296e4a23: C = DE, ST = REDACTED, L = REDACTED, O = REDACTED, CN = REDACTED
error 20 at 0 depth lookup:unable to get local issuer certificate
```

Working invocation:
```
$ cat intermediate5e3c3296e4ae5 intermediate5e3c3296e4ab1 intermediate5e3c3296e4a60 >intermediate
$ openssl verify -verbose -CAfile ca5e3c3296e4415 -untrusted intermediate  cert5e3c3296e4a23
cert5e3c3296e4a23: OK
```

**Comment by lota** [comment]
I tried this patch to solve my issues #81 that seems related (Sectigo CA Root expired May 30, 2020), but not seems solved.
