### ISSUE TITLE
x509 process dies every day

### ISSUE THREAD

**Issue by MarcusCaepio** [Icinga/icingaweb2-module-x509#79]
Hi all,
I have x509 running as service and get a recurring error, which let the process die every day, when the jobs run.

```
$ journalctl -u icinga-x509.service
icingacli[2888]: ERROR: ErrorException in /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php:309 with message: Error while sending STMT_PREPARE packet. PID=28
systemd[1]: icinga-x509.service: Main process exited, code=exited, status=1/FAILURE

```
## To Reproduce
Define a few jobs and let x509 run as systemd process

## Expected behavior
Don't die

## Your Environment
* Icinga Web 2 version and modules (System - About): 
businessprocess | 2.2.0
grafana | 1.3.6
idoreports | 0.9.1
incubator | 0.5.0
ipl | v0.5.0
jira | 1.0.1
monitoring | 2.7.3
pdfexport | 0.9.1
reactbundle | 0.7.0
reporting | 0.9.2
x509 | 1.0.0

* Icinga 2 version used (`icinga2 --version`): r2.11.3-1
* PHP version used (`php --version`): PHP 7.0.33-0ubuntu0.16.04.14
* Server operating system and version: Ubuntu 16.04. LTS

Regards,
Marcus

**Comment by sephiroth1395** [comment]
If it can help troubleshooting, I have the same behaviour since I deleted an unused certificate from the SQL DB.

**Comment by flybyray** [comment]
just a guess this is because the service is just a long running process and it will not reconnect the sql connection which is timed out if waits typically a day or maybe a weekend.

ipl might have some function called ping for reconnecting . but i guess it is not run before the prepare statement:
https://github.com/Icinga/ipl-sql/blob/master/src/Connection.php#L191

**Comment by flybyray** [comment]
the above patch modified the error message:

```LOG
Okt 30 08:37:00 HOST icingacli[57497]: ERROR: PDOException in /etc/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php:310 with message: SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active.  Consider using PDOStatement::fetchAll().  Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setti...
```

**Comment by mwaldmueller** [comment]
+1

Environment:
* Icinga Web 2 version and modules (System - About): 2.8.2
* Icinga 2 version used (`icinga2 --version`): 2.12.3
* PHP version used (`php --version`): 7.3.20
* Server operating system and version: CentOS 7.9
* Modules:
   * x509: master, commit cc1ae770e29fefcc321d55fa89bf4dea9c3710b4
   * ipl: 0.5.0

**Comment by gianmarco-mameli** [comment]
Hi, same problem to me, error:
ERROR: ErrorException in /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php:401 with message: Error while sending STMT_PREPARE packet. PID=232525

Thanks

**Comment by bobapple** [comment]
ref/IP/39026

**Comment by slalomsk8er** [comment]
> ref/IP/39026

I can confirm, that the problem is gone after the update. The service runs now for 6h and before the update it would fail after  1-2h.
