### ISSUE TITLE
Check doesn't switch back to "OK" after certificate renewal

### ISSUE THREAD

**Issue by wlma** [Icinga/icingaweb2-module-x509#80]
## Describe the bug
I'm facing the problem that after renewal of a certificate (LetsEncrypt) the state doesn't switch back from critical' to 'ok'. Check Command itself shows correct expiry-time (82 days), but stays in state "crtitical"
from console:
`icingacli x509 check host --host c3po.wuapaa.com --warning 14d --critical 7d
CRITICAL - c3po.wuapaa.com expires in 82 days|'c3po.wuapaa.com'=7148392s;1209600;604800;0;7776000`

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. install x509 module
2. let certificate expire
3. renew certificate

## Expected behavior

Check should switch back to state "ok"

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About):

director | 1.7.2
doc | 2.7.3
grafana | 1.1.7
graylog | 0.0.1
incubator | 0.5.0
ipl | v0.4.0
monitoring | 2.7.3
nagvis | 1.1.1
reactbundle | 0.7.0
x509 | 1.0.0
`
* Web browser used:
   does not apply
* Icinga 2 version used (`icinga2 --version`):

icinga2 - The Icinga 2 network monitoring daemon (version: r2.11.3-1)

Copyright (c) 2012-2020 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Debian GNU/Linux
  Platform version: 10 (buster)
  Kernel: Linux
  Kernel version: 5.3.13-2-pve
  Architecture: x86_64

Build information:
  Compiler: GNU 8.3.0
  Build host: runner-LTrJQZ9N-project-298-concurrent-0

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

* PHP version used (`php --version`):

PHP 7.3.14-1~deb10u1 (cli) (built: Feb 16 2020 15:07:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.14, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.14-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies

* Server operating system and version:

Debian 10 x86_64

**Comment by lippserd** [comment]
Should be fixed with #94.
