### ISSUE TITLE
Certificate chain valid as CA certs are expired

### ISSUE THREAD

**Issue by deuntje** [Icinga/icingaweb2-module-x509#82]
## Describe the bug
While the sectigo cert expired May 30, some certificates had the old CA/intermediate certs in their chain, older systems do have problems with this. Icinga does see this chain as valid (see screenshot below).

## Expected behavior
Give a warning or critical level when certificate and/or an (intermediate) CA certificate is expired.

## Screenshots
![afbeelding](https://user-images.githubusercontent.com/17932042/84747831-18044e00-afb8-11ea-8123-217b018e4b76.png)

## Environment

* Icinga Web 2 version and modules (System - About): icinga web 2 2.8.0 , x509 1.0.0
* Web browser used: Firefox 77.0.1 (64-bits)
* Icinga 2 version used (`icinga2 --version`): r2.11.3-1
* PHP version used (`php --version`): 7.4.7
* Server operating system and version: Debian 9.12

**Comment by lippserd** [comment]
Duplicates #64
