### ISSUE TITLE
Verify_host_ssl can only handle warning or critical, not both.

### ISSUE THREAD

**Issue by JensBavenmark** [Icinga/icingaweb2-module-x509#89]
## Describe the bug
When using the Verify Host SSL check there is an issue when setting fixed times for warning and critical values.
When setting just warning or critical it works okay. But if you set both warning and critical values only the one that is first in the command line is being used. The other one uses the default value.

Some examples:

Check: verify_host_ssl.sh' '--host' 'myexample.example.com' '--ip' '10.10.10.10' --critical "6d" '--warning' '42d'
Reponse: OK - myexample.example.com expires in 30 days |'myexample.example.com'=2639540s;1900800;518400;0;7776000

Check: verify_host_ssl.sh' '--host' 'myexample.example.com' '--ip' '10.10.10.10' '--warning' '42d' '--critical' '32d'
Response: WARNING - myexample.example.com expires in 30 days|'myexample.example.com'=2639132s;3628800;777600;0;7776000

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. Setup a verify_host_ssl check
2. Set fixed valus (f.ex. 7d, 14d) for both warnings and critical
3. Test check and see that it just "cares" about the first value in the command line.

## Expected behavior
That both values should be used by the check

## Your Environment

* Icinga Web 2 version and modules (System - About):
Icinga Web 2 Version 2.8.2
x509 1.0.0

* Web browser used:
Firefox

* Icinga 2 version used (`icinga2 --version`):
2.12.0.-1

* PHP version used (`php --version`):
7.3.11

* Server operating system and version:
CentOS 7.8

**Comment by lippserd** [comment]
I don't know if I'm missing something, but `verify_host_ssl` is not from us.
