### ISSUE TITLE
import ca-certificates.crt

### ISSUE THREAD

**Issue by bgoerner** [Icinga/icingaweb2-module-x509#91]
i try to import my ca-certificates.crt, Error:

icingacli x509 import --file /etc/ssl/certs/ca-certificates.crt
ERROR: PDOException in /usr/share/icingaweb2/modules/ipl/vendor/ipl/sql/src/Connection.php:310 with message: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'valid_to' at row 1

**Comment by michael1809** [comment]
same problem ... any solution?

**Comment by michael1809** [comment]
solution: change field to signed ...

**Comment by bgoerner** [comment]
> solution: change field to signed ...

what is the solution? can you explain? thanks.

**Comment by michael1809** [comment]
https://github.com/Icinga/icingaweb2-module-x509/issues/60#issuecomment-524208003
It seems it is the same problem.
